Repository GEOS-ESM/mepo, pull requests merged in 2020-11, with the labels that each got.

#122 mepo assumed everything is detached at init
  mepo.d/state/component.py
Labels: bugfix

#123 GitFlow: Pull hotfix from main into develop
  mepo.d/state/component.py
Labels: bugfix

#124 Add --staged option to mepo diff
  mepo.d/cmdline/parser.py
  mepo.d/repository/git.py
Labels: enhancement

#125 Merge develop into main for release
  mepo.d/cmdline/parser.py
  mepo.d/repository/git.py
Labels: enhancement

#126 Add force flag for fetch and fetch-all
  mepo.d/cmdline/parser.py
  mepo.d/repository/git.py
Labels: enhancement

#127 Merge Develop into Main
  mepo.d/cmdline/parser.py
  mepo.d/repository/git.py
Labels: enhancement

#129 Fixes #128. Allow all-in-one clone with a config
  mepo.d/command/clone/clone.py
Labels: bugfix

#132 Merge Develop for all-in-one config fix
  mepo.d/command/clone/clone.py
Labels: bugfix

#134 Fix for clone-config bug
  mepo.d/cmdline/parser.py
  mepo.d/command/clone/clone.py
Labels: bugfix

#135 Pull hotfix from main into develop
  mepo.d/cmdline/parser.py
  mepo.d/command/clone/clone.py
Labels: bugfix

#136 Feature/wjamieson/requirements #56
  requirements.txt
Labels: enhancement

#131 Add support for `mepo commit -a`
  mepo.d/cmdline/parser.py
  mepo.d/command/commit/commit.py
  mepo.d/command/stage/stage.py
Labels: enhancement

#137 Merge Develop into main for 'commit -a'
  mepo.d/cmdline/parser.py
  mepo.d/command/commit/commit.py
  mepo.d/command/stage/stage.py
  requirements.txt
Labels: enhancement

#138 Pull in zenodo update from main
  .zenodo.json
Labels: documentation
