Repository GEOS-ESM/mepo, pull requests merged in 2025-01, with the labels that each got.

#335 Fixes for less used options of "mepo clone"
  CHANGELOG.md
  pyproject.toml
  src/mepo/command/clone.py
  tests/input/external-components.yaml
  tests/output/output_branch_list.txt
  tests/test_mepo_clone.py
  tests/test_mepo_commands.py
Labels: bugfix

#336 v1: Make mepo status serial by default
  CHANGELOG.md
  mepo.d/command/status/status.py
Labels: enhancement, bugfix

#341 Merge develop into main - 2025Jan06
  CHANGELOG.md
  pyproject.toml
  src/mepo/command/clone.py
  tests/input/external-components.yaml
  tests/output/output_branch_list.txt
  tests/test_mepo_clone.py
  tests/test_mepo_commands.py
Labels: gitflow

#338 v2: Default status and restore-state to serial
  CHANGELOG.md
  src/mepo/cmdline/parser.py
  src/mepo/command/restore-state.py
  src/mepo/command/status.py
  tests/test_mepo_clone.py
  tests/test_mepo_commands.py
Labels: enhancement, bugfix
